# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
gcpreviews:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/builder-jx

controllerbuild:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/builder-go

controllerteam:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/builder-jx


controllerrole:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/builder-jx

gcactivities:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/builder-jx

gcpods:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/builder-jx

expose:
  Image: gcr.azk8s.cn/jenkinsxio/exposecontroller


exposecontroller:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/exposecontroller

Ingress:
  enable: true
  image:
    repository: gcr.azk8s.cn/google_containers/defaultbackend


nexus:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/nexus

jenkins:
  Master:
    Image: "jenkinsxio/jenkinsx"
    ServiceType: NodePort
  Agent:
    PodTemplates:
      Gradle:
        Containers:
          Gradle:
            Image: gcr.azk8s.cn/jenkinsxio/builder-gradle:0.1.577

heapster:
  image:
    repository: gcr.azk8s.cn/google_containers/heapster
  resizer:
    image:
      repository: gcr.azk8s.cn/google_containers/addon-resizer